version: '3.6'
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 853:853/tcp
      - 3000:3000/tcp
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/adguard/work:/opt/adguardhome/work
      - ${CONFIG_PATH}/adguard/conf:/opt/adguardhome/conf