version: '3.6'
services:
    nextcloud:
        container_name: nextcloud
        restart: unless-stopped
        image: nextcloud:latest
        links:
            - mariadb
            - redis
        volumes:
            - '${NEXTCLOUD_DATA_PATH}:/var/www/html'
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - REDIS_HOST=redis
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.backend=nextcloud"
            - "traefik.frontend.rule=Host:${DOMAINNAME}"
            - "traefik.docker.network=web"
            - "traefik.port=80"
            - "traefik.frontend.redirect.permanent=true"
            - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
            - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
            - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000"

    redis:
      image: arm32v7/redis:latest
      hostname: redis
      container_name: "redis"
      restart: unless-stopped
      networks: 
        - web

    mariadb:
       image: jsurf/rpi-mariadb:latest
       container_name: "mariadb"
       hostname: mariadb
       volumes:
            - ${DATA_PATH}/mysql:/var/lib/mysql
       networks: 
            - web
       ports:
         - target: 3306
           published: 3306
           protocol: tcp
           mode: host
       restart: unless-stopped
       environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}

networks:
    web:
        name: web
