version: '3.6'
services:
    nextcloud:
        container_name: nextcloud
        restart: unless-stopped
        image: nextcloud:latest
        links:
            - mariadb
            - redis
        volumes:
            - '${NEXTCLOUD_DATA_PATH}:/var/www/html'
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - REDIS_HOST=redis
        networks:
            - web

    redis:
      image: arm32v7/redis:latest
      hostname: redis
      container_name: "redis"
      restart: unless-stopped
      networks: 
        - web

    mariadb:
       image: jsurf/rpi-mariadb:latest
       container_name: "mariadb"
       hostname: mariadb
       volumes:
            - ${DATA_PATH}/mysql:/var/lib/mysql
       networks: 
            - web
       ports:
         - target: 3306
           published: 3306
           protocol: tcp
           mode: host
       restart: unless-stopped
       environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}

networks:
    web:
        name: web
