version: '3.6'
services:
    komga:
        image: gotson/komga
        container_name: komga
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG_PATH}/Gotson:/config:rw
            - ${MEDIA_PATH}/Comics:/comics:rw
            - ${MEDIA_PATH}/Manga:/manga:rw
            - ${MEDIA_PATH}/Bedes:/bedes:rw
        ports:
            - 8080:8080
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        network_mode: host
        restart: unless-stopped
    calibre-web:
        image: linuxserver/calibre-web:latest
        container_name: calibre-web
        entrypoint:
            - /init
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        ports:
            - 8083:8083
        restart: unless-stopped
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG_PATH}/Calibre-Web:/config:rw
            - ${MEDIA_PATH}/Books:/books:rw
