---
version: "3.6"
services:

  jellyfin:
      image: lscr.io/linuxserver/emby:latest
      container_name: "emby"
      restart: unless-stopped
      networks:
        - emby-net
      ports:
        - 8096:8096
        - 8920:8920 #optional
      dns:
        - 1.1.1.1
        - 8.8.8.8
      volumes:
        - ${CONFIG_PATH}:/config
        - ${TVSHOWS_PATH}:/data/tvshows
        - ${MOVIES_PATH}:/data/movies
      environment:
        - PGID=${PGID}
        - PUID=${PUID}          
        - TZ=${TZ}

networks:
  emby-net: