version: '3.6'
services:
    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        volumes:
            - ${BACKUP_PATH}:/backups
            - ${SOURCE_PATH}:/source
            - ${CONFIG_PATH}/Duplicati:/config:rw
        ports:
            - 8200:8200
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        network_mode: host
        restart: unless-stopped
    watchtower:
        image: v2tec/watchtower:armhf-latest
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: host
        command: --interval 43200
        restart: unless-stopped