version: '3.6'
services:
    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        volumes:
            - ${BACKUP_PATH}:/backups
            - ${SOURCE_PATH}:/source
            - ${CONFIG_PATH}/Duplicati:/config:rw
        ports:
            - 8200:8200
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        networks:
          - stack-net
        restart: unless-stopped
    watchtower:
        image: v2tec/watchtower:armhf-latest
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - stack-net
        command: --interval 43200
        restart: unless-stopped
    uptime-kuma:
      image: louislam/uptime-kuma:latest
      container_name: uptime-kuma
      ports:
        - 3001:3001
      volumes:
        - ${CONFIG_PATH}/UptimeKuma:/app/data:rw
      networks:
          - stack-net
      restart: unless-stopped
 

networks:
  stack-net: