global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['<IP Address of your server>:9100']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['<IP Address of your server>:9100'] 