---
version: "3.6"
services:

  jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: "jellyfin"
      restart: unless-stopped
      networks:
        - jellyfin-net
      ports:
        - 8096:8096
        - 7359:7359/udp #Allows clients to discover Jellyfin on the local network.
        - 1900:1900/udp #Service discovery used by DNLA and clients.
      dns:
        - 1.1.1.1
        - 8.8.8.8
      volumes:
        - ${CONFIG_PATH}:/config
        - ${TVSHOW_PATH}:/data/tvshows
        - ${MOVIES_PATH}:/data/movies
      environment:
        - PGID=${PGID}
        - PUID=${PUID}          
        - TZ=${TZ}
        - JELLYFIN_PublishedServerUrl=${SRV_URL}

networks:
  jellyfin-net:
